# Generated by Django 2.2.1 on 2019-05-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.TextField(db_index=True)),
                ('description', models.TextField(db_index=True)),
            ],
        ),
    ]
