# Generated by Django 2.2.1 on 2019-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtg', '0001_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.TextField(db_index=True)),
                ('description', models.TextField(db_index=True)),
                ('image', models.ImageField(upload_to='')),
                ('likes_count', models.PositiveIntegerField()),
                ('participants_count', models.PositiveIntegerField()),
                ('max_participants_count', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('similar_with', models.ManyToManyField(to='wtg.Event')),
                ('tags', models.ManyToManyField(to='wtg.Tag')),
            ],
        ),
    ]
