# Generated by Django 2.2.1 on 2019-05-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtg', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='likes_count',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants_count',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
