# Generated by Django 2.2.1 on 2019-05-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtg', '0004_event_admin_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
