# Generated by Django 2.2.1 on 2019-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtg', '0005_event_numbers_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
